### ISSUE TITLE
feature: create input for food sensitivities

### ISSUE THREAD

**Issue by mekelaiorio** [It-s-Saturday/Fornear#35]
**Describe the feature**
Add an input for dietary needs, allergies, or food sensitivities.
@jibranabsarulislam

**Comment by jibranabsarulislam** [comment]
field can be added in two places in `frontend/Request.jsx`

https://github.com/It-s-Saturday/Fornear/blob/dcf9abae04deff7380f6eb056c90e7ed6cd10079/frontend/src/components/Request.jsx#L36-L42

https://github.com/It-s-Saturday/Fornear/blob/dcf9abae04deff7380f6eb056c90e7ed6cd10079/frontend/src/components/Request.jsx#L131-L176

**Comment by karthickbharathi1** [comment]
Hi @jibranabsarulislam can you assign me this issue?

**Comment by jibranabsarulislam** [comment]
@karthickbharathi1 absolutely, thanks for reaching out!
