### ISSUE TITLE
feature: default text for when data is falsy

### ISSUE THREAD

**Issue by jibranabsarulislam** [It-s-Saturday/Fornear#39]
**Describe the feature**
when backend is not running or API call fails (when `data === null` or `data` is falsy), show default text on the screen

**What would the feature solve**
- UX
- development efficiency

**Comment by neeravbhaskarla** [comment]
can you assign me this issue?

**Comment by jibranabsarulislam** [comment]
you got it @neeravbhaskarla 🏃

**Comment by neeravbhaskarla** [comment]
> **Describe the feature** when backend is not running or API call fails (when `data === null` or `data` is falsy), show default text on the screen
> 
> **What would the feature solve**
> 
> * UX
> * development efficiency

What should be the default text display? Should it show 'No data' or is it acceptable to have no visible data?

**Comment by neeravbhaskarla** [comment]
Hi @jibranabsarulislam, What should be the default text display? Should it show 'No data' or is it acceptable to have no visible data?

**Comment by jibranabsarulislam** [comment]
thanks for reaching out @neeravbhaskarla, what do you think of "There are no items to display.", probably with a `className='text-bold'`

**Comment by neeravbhaskarla** [comment]
if data is not there should I not display any items?

**Comment by jibranabsarulislam** [comment]
right, for now we can show the no items text when there's no response data
