### ISSUE TITLE
bug: on npm start, homepage lands on localhost:3000/Fornear

### ISSUE THREAD

**Issue by jibranabsarulislam** [It-s-Saturday/Fornear#50]
**Describe the bug**

homepage lands on localhost:3000/Fornear instead of localhost:3000/

**Expected behavior**

should bring developer to '/'

**Comment by neeravbhaskarla** [comment]
can I get it assigned>

**Comment by neeravbhaskarla** [comment]
Hi @jibranabsarulislam, I raised a PR for this issue. Please Check
