### ISSUE TITLE
bug: navlink new implementation console errors

### ISSUE THREAD

**Issue by jibranabsarulislam** [It-s-Saturday/Fornear#57]
**Screenshots**
![image](https://github.com/It-s-Saturday/Fornear/assets/70596906/9a890175-aae4-4a37-b6e0-b8e29a83587c)

**Comment by neeravbhaskarla** [comment]
Can you assign this issue to me?

**Comment by jibranabsarulislam** [comment]
@neeravbhaskarla ✅

**Comment by neeravbhaskarla** [comment]
hi @jibranabsarulislam Submitted PR with the required changes to solve the bug. Please check
