### ISSUE TITLE
feature: expiration date

### ISSUE THREAD

**Issue by jibranabsarulislam** [It-s-Saturday/Fornear#7]
**Describe the feature**
- some way of tracking expiration date
- would be a bit difficult to orchestrate item count and expiration dates
- suggestions during fulfillment to pack earliest expiration date

**What would the feature solve**
- maximize resourcefulness of pantry inventory (avoid waste)
- safeguard student health by adding an extra check on expiration

**Comment by jibranabsarulislam** [comment]
@mekelaiorio what input do you got ab expiration dates?

**Comment by mekelaiorio** [comment]
I don’t think it’s worth it at the moment! Most of their inventory includes non-perishables and they already order food by date on the shelves.
